### ISSUE TITLE
datetime.datetime.utcnow() is deprecated

### ISSUE THREAD

**Issue by bepstein** [theias/ias_duo_phone_cleanup#2]
We are getting warnings from the script of a deprecated call regarding time.

`/home/ep/code/ias/git/ias_duo_phone_cleanup/duo_phone_cleanup/__main__.py:305: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  grace_period_time = datetime.utcnow() - timedelta(
2024-09-21 17:40:06,INFO,Updating new phone for the user `dallan` with id `DPAURW5PJCU42UJTOY9G` with timestamp, to mark for cleanup on the next run
/home/ep/code/ias/git/ias_duo_phone_cleanup/duo_phone_cleanup/__main__.py:242: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  name=str(round(datetime.timestamp(datetime.utcnow()))),
`

We should look into updating the code.

**Comment by cspeterson** [comment]
this deprecation is new with 3.12 and we are targeting 3.11 at best

we should ignore this
